# This script must be placed in the same directory as all the other txt files with the song names
# Make sure you export your client id, client secret and client redirect uri using "export SPOTIFY_CLIENT_ID=<ID>", "export SPOTIFY_CLIENT_SECRET=<id>" and "export SPOTIFY_REDIRECT_URI='http://127.0.0.1:8080'"

from multiprocessing.sharedctypes import Value
import spotipy
from spotipy.oauth2 import SpotifyOAuth
import os
import json

# Vars
scope = 'playlist-modify-public'
username = 'Your spotify username here'
token = 'Your client ID here'

# Boring spotify stuff
token = SpotifyOAuth(scope=scope, username=username)
spotifyObject = spotipy.Spotify(auth_manager = token)

# Create spotify playlist
spotifyObject.user_playlist_create(user=username,name="ICT2207 Lab 1 Playlist",public=True,description="This playlist is generated by Ryan's script")

# Add the songs to a list
list_of_songs = []
counter = 1
for filename in os.listdir('.'):
    if (counter > 100):
        break
    else:
        try:
            with open(filename) as f:
                print(filename)
                first_line = f.readline()
                print(first_line)
                
                result = spotifyObject.search(q=first_line)
                #print(json.dumps(result,sort_keys=4,indent=4))
                #print(result['tracks']['items'][0]['uri'])
                list_of_songs.append(result['tracks']['items'][0]['uri'])
                counter += 1
        except (IndexError, IsADirectoryError) as e:
            continue

# Find the playlist we created earlier
prePlaylist = spotifyObject.user_playlists(user=username)
playlist = prePlaylist['items'][0]['id']

# Add the songs to the playlist
spotifyObject.user_playlist_add_tracks(user=username,playlist_id=playlist,tracks=list_of_songs)